[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://concurseiro-backend.onrender.com/api/v1"
  REACT_APP_APP_NAME = "Duolingo Jurídico"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 